In [14]:
import pandas as pd
import numpy as np

# Groupby method -categories

In [4]:
dataset = pd.read_csv(r"D:\AIML-internship\AllData\weather_by_cities.csv")

In [5]:
dataset

           day      city  temperature  windspeed   event  Unnamed: 5
0   01-01-2017  new york           32          6    Rain         NaN
1   01-02-2017  new york           36          7   Sunny         NaN
2   01-03-2017  new york           28         12    Snow         NaN
3   01-04-2017  new york           33          7   Sunny         NaN
4   01-01-2017    mumbai           90          5   Sunny         NaN
5   01-02-2017    mumbai           85         12     Fog         NaN
6   01-03-2017    mumbai           87         15     Fog         NaN
7   01-04-2017    mumbai           92          5    Rain         NaN
8   01-01-2017     paris           45         20   Sunny         NaN
9   01-02-2017     paris           50         13  Cloudy         NaN
10  01-03-2017     paris           54          8  Cloudy         NaN
11  01-04-2017     paris           42         10  Cloudy         NaN

In [6]:
group = dataset.groupby('city')

In [7]:
group

for city,data in group:
    print('city : ',city,"\ndata:",data)

In [9]:
group.get_group('mumbai')

          day    city  temperature  windspeed  event  Unnamed: 5
4  01-01-2017  mumbai           90          5  Sunny         NaN
5  01-02-2017  mumbai           85         12    Fog         NaN
6  01-03-2017  mumbai           87         15    Fog         NaN
7  01-04-2017  mumbai           92          5   Rain         NaN

In [12]:
group.max()

                 day  temperature  windspeed  event  Unnamed: 5
city
mumbai    01-04-2017           92         15  Sunny         NaN
new york  01-04-2017           36         12  Sunny         NaN
paris     01-04-2017           54         20  Sunny         NaN

In [11]:
group.min()

                 day  temperature  windspeed   event  Unnamed: 5
city
mumbai    01-01-2017           85          5     Fog         NaN
new york  01-01-2017           28          6    Rain         NaN
paris     01-01-2017           42          8  Cloudy         NaN

In [13]:
group.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed         ...              Unnamed: 5                       \
             count   mean  ...    75%   max      count mean std min 25% 50%
city                       ...
mumbai         4.0   9.25  ...  12.75  15.0        0.0  NaN NaN NaN NaN NaN
new york       4.0   8.00  ...   8.25  12.0        0.0  NaN NaN NaN NaN NaN
paris          4.0  12.75  ...  14.75  20.0        0.0  NaN NaN NaN NaN NaN


         75% max
city
mumbai   NaN NaN
new york NaN NaN
paris    NaN NaN

[3 rows x 24 columns]

In [15]:
group.mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_14048\3928442431.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  group.mean()

          temperature  windspeed  Unnamed: 5
city
mumbai          88.50       9.25         NaN
new york        32.25       8.00         NaN
paris           47.75      12.75         NaN

In [16]:
weather_data1 = pd.DataFrame({
    "city":["sangli","Kolhapur","Jaysingpur","Miraz","Ichalkaranji"],
    "temperature": [35,37,34,40,33],
    "windspeed":[9.25,8.00,12.34,7.5,8.00]
})

In [17]:
weather_data2 = pd.DataFrame({
    "city":["panhala","poele","bhamate","satara","ratnagiri"],
    "temperature": [35,37,34,40,33],
    "windspeed":[9.25,8.00,12.34,7.5,8.00]
})

In [19]:
data = pd.concat([weather_data1,weather_data2])
data

           city  temperature  windspeed
0        sangli           35       9.25
1      Kolhapur           37       8.00
2    Jaysingpur           34      12.34
3         Miraz           40       7.50
4  Ichalkaranji           33       8.00
0       panhala           35       9.25
1         poele           37       8.00
2       bhamate           34      12.34
3        satara           40       7.50
4     ratnagiri           33       8.00

In [20]:
data = pd.concat([weather_data1,weather_data2],ignore_index = True)
data

           city  temperature  windspeed
0        sangli           35       9.25
1      Kolhapur           37       8.00
2    Jaysingpur           34      12.34
3         Miraz           40       7.50
4  Ichalkaranji           33       8.00
5       panhala           35       9.25
6         poele           37       8.00
7       bhamate           34      12.34
8        satara           40       7.50
9     ratnagiri           33       8.00

In [22]:
weather_data1 = pd.DataFrame({
    "city":["sangli","Kolhapur","Jaysingpur","Miraz","Ichalkaranji"],
    "temperature": [35,37,34,40,33],
    "windspeed":[9.25,8.00,12.34,7.5,8.00],"index":[0,2,3,1,4]
}
)

In [23]:
weather_data1

           city  temperature  windspeed  index
0        sangli           35       9.25      0
1      Kolhapur           37       8.00      2
2    Jaysingpur           34      12.34      3
3         Miraz           40       7.50      1
4  Ichalkaranji           33       8.00      4

In [27]:
weather_data1 = pd.DataFrame({
    "city":["sangli","Kolhapur"],
    "temperature": [35,37]
},index =[1,0]
)

In [25]:
weather_data1

       city  temperature  index
0    sangli           35      1
1  Kolhapur           37      0

In [34]:
df1 = pd.DataFrame({
    "city":["sangli","Kolhapur","Jaysingpur","Miraz","Ichalkaranji","mumbai"],
    "temperature": [35,37,34,40,33,40]
})

In [35]:
df2 = pd.DataFrame({
    "city":["sangli","Kolhapur","Jaysingpur","Miraz","pune"],
    "temperature": [33,34,35,36,23]
   
})

In [36]:
df3 = pd.merge(df1,df2,on='city')

In [37]:
df3

         city  temperature_x  temperature_y
0      sangli             35             33
1    Kolhapur             37             34
2  Jaysingpur             34             35
3       Miraz             40             36

In [43]:
df4 = pd.merge(df1,df2,on='city',how='right')

In [44]:
df4

         city  temperature_x  temperature_y
0      sangli           35.0             33
1    Kolhapur           37.0             34
2  Jaysingpur           34.0             35
3       Miraz           40.0             36
4        pune            NaN             23