In [18]:
from numpy import *
import pandas as pd
import numpy as np

In [2]:
# dataframe
data = {
    "name":["Ajay","Vijay","Ram","Sham","Sita","Gita"],
    "id" : [1,2,3,4,5,6],
    "Salary" : [10000,2000000,230999,234885,2361,85346]
}
print(data)

{'name': ['Ajay', 'Vijay', 'Ram', 'Sham', 'Sita', 'Gita'], 'id': [1, 2, 3, 4, 5, 6], 'Salary': [10000, 2000000, 230999, 234885, 2361, 85346]}

In [3]:
dataset = DataFrame(data)

In [4]:
dataset

    name  id   Salary
0   Ajay   1    10000
1  Vijay   2  2000000
2    Ram   3   230999
3   Sham   4   234885
4   Sita   5     2361
5   Gita   6    85346

In [5]:
dataset["Salary"]

0      10000
1    2000000
2     230999
3     234885
4       2361
5      85346
Name: Salary, dtype: int64

In [6]:
dataset["Salary"].sum()

2563591

In [7]:
dataset["Salary"].count()

6

In [8]:
dataset["Salary"].std()

777250.0086050605

In [9]:
dataset["Salary"].min()

2361

In [10]:
dataset["Salary"].mode()

0       2361
1      10000
2      85346
3     230999
4     234885
5    2000000
Name: Salary, dtype: int64

In [11]:
dataset["Salary"].max()

2000000

In [12]:
dataset.head()

    name  id   Salary
0   Ajay   1    10000
1  Vijay   2  2000000
2    Ram   3   230999
3   Sham   4   234885
4   Sita   5     2361

In [13]:
dataset.tail(2)

   name  id  Salary
4  Sita   5    2361
5  Gita   6   85346

In [14]:
dataset.describe()

             id        Salary
count  6.000000  6.000000e+00
mean   3.500000  4.272652e+05
std    1.870829  7.772500e+05
min    1.000000  2.361000e+03
25%    2.250000  2.883650e+04
50%    3.500000  1.581725e+05
75%    4.750000  2.339135e+05
max    6.000000  2.000000e+06

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   id      6 non-null      int64
 2   Salary  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes

In [16]:
dataset["Salary"].mean()

427265.1666666667

m=round(dataset["Salary"].mean())
m

In [19]:
df = pd.read_csv("D:\AIML-internship\AllData\weather_data.csv")

In [20]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [21]:
df1 = pd.read_excel("D:\AIML-internship\AllData\weather_data.xlsx","Sheet1")
df1

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [22]:
# tuple list
weather_data = [
    ("2017-01-01",32,6,"Rain"),
    ("2017-01-02",35,7,"Sunny"),
    ("2017-01-03",28,2,"Snow")
]

In [23]:
w = pd.DataFrame(data = weather_data,columns=["day","temp","windspeed","event"])

In [24]:
w

          day  temp  windspeed  event
0  2017-01-01    32          6   Rain
1  2017-01-02    35          7  Sunny
2  2017-01-03    28          2   Snow

In [26]:
# list of dictionaries
we = [
    {"day":'1/2/2022',"temparature":33,"windspeed":34},
    {"day":'2/2/2022',"temparature":33,"windspeed":34},
    {"day":'3/2/2022',"temparature":33,"windspeed":34},
    {"day":'4/2/2022',"temparature":33,"windspeed":34}

]

In [27]:
we

[{'day': '1/2/2022', 'temparature': 33, 'windspeed': 34},
 {'day': '2/2/2022', 'temparature': 33, 'windspeed': 34},
 {'day': '3/2/2022', 'temparature': 33, 'windspeed': 34},
 {'day': '4/2/2022', 'temparature': 33, 'windspeed': 34}]

In [29]:
df1 = pd.DataFrame(data = we)

In [30]:
df1

        day  temparature  windspeed
0  1/2/2022           33         34
1  2/2/2022           33         34
2  3/2/2022           33         34
3  4/2/2022           33         34